### ISSUE TITLE
error loading when installed via vis-plug

### ISSUE THREAD

**Issue by ghost** [jpaulogg/vis-ins-completion#1]
error message from vis

```
/home/opn/.cache/vis-plug/plugins/vis-ins-completion/init.lua:5: module 'plugins/ins-completion/complete-dict' not found:
	no field package.preload['plugins/ins-completion/complete-dict']
	no file '/home/opn/.cache/vis-plug/plugins/ins-completion/complete-dict.lua'
	no file '/home/opn/.cache/vis-plug/plugins/ins-completion/complete-dict/init.lua'
	no file '/usr/bin/lua/plugins/ins-completion/complete-dict.lua'
	no file '/usr/bin/lua/plugins/ins-completion/complete-dict/init.lua'
	no file '/home/opn/.config/vis/plugins/ins-completion/complete-dict.lua'
	no file '/home/opn/.config/vis/plugins/ins-completion/complete-dict/init.lua'
	no file '/etc/vis/plugins/ins-completion/complete-dict.lua'
	no file '/etc/vis/plugins/ins-completion/complete-dict/init.lua'
	no file '/usr/share/vis/plugins/ins-completion/complete-dict.lua'
	no file '/usr/share/vis/plugins/ins-completion/complete-dict/init.lua'
	no file '/usr/share/lua/5.4/plugins/ins-completion/complete-dict.lua'
	no file '/usr/share/lua/5.4/plugins/ins-completion/complete-dict/init.lua'
	no file '/usr/lib64/lua/5.4/plugins/ins-completion/complete-dict.lua'
	no file '/usr/lib64/lua/5.4/plugins/ins-completion/complete-dict/init.lua'
	no file ''
	no file '/usr/lib64/lua/5.4/plugins/ins-completion/complete-dict.so'
	no file '/usr/lib64/lua/5.4/loadall.so'
	no file ''
```

**Comment by jpaulogg** [comment]
Hi!

The path to the plugin directory is definde [here](https://github.com/jpaulogg/vis-ins-completion/blob/da0690bc587db07155f29176d059be2c2a8dbc8e/init.lua#L3). The default path is `~/.config/vis/plugins/vis-ins-completion/`.
~~I see that you are using [vis-plug](https://github.com/erf/vis-plug). You can try one of these:~~

1. ~~Manually edit `~/.cache/vis-plug/plugins/vis-ins-completion/init.vim` file. Replace the default path `plugins/vis-ins-completion/` with `/home/opn/vis-plug/plugins/vis-ins-completion/`~~
2. ~~Change your vis-plug directory  in your visrc: ```plug.set_path('~/.config/vis')```. Then, reinstall all your plugins.~~
3. ~~Follow [these](https://github.com/jpaulogg/vis-ins-completion#installation) instructions to install the plugin without vis-plug.~~

The error was happening because the default path was wrongly defined as `plugins/ins-completion`. Fixed in https://github.com/jpaulogg/vis-ins-completion/commit/da0690bc587db07155f29176d059be2c2a8dbc8e.

**Comment by ghost** [comment]
Thanks. I followed number 2.

**Comment by ghost** [comment]
I didn't understand this line in error message,

```
no file '/home/opn/.cache/vis-plug/plugins/ins-completion/complete-dict.lua'
```

**Comment by jpaulogg** [comment]
> I didn't understand this line in error message,
> 
> ```
> no file '/home/opn/.cache/vis-plug/plugins/ins-completion/complete-dict.lua'
> ```

It seems that all errors happened because the default path was wrongly defined as `plugins/ins-completion`. My mistake. I fixed this in https://github.com/jpaulogg/vis-ins-completion/commit/da0690bc587db07155f29176d059be2c2a8dbc8e.

So you probably did not need to follow any of the steps I described earlier :sweat_smile:.

**Comment by ghost** [comment]
how did it work when i followed number 2?

it was looking for 

```
/home/opn/.config/vis/plugins/ins-completion/complete-dict.lua
```
but that file was at

```
/home/opn/.config/vis/plugins/vis-ins-completion/complete-dict.lua
```

**Comment by jpaulogg** [comment]
> how did it worked when i followed number 2.
> 
> it was looking for
> 
> ```
> /home/opn/.config/vis/plugins/ins-completion/complete-dict.lua
> ```
> 
> but that file was at
> 
> ```
> /home/opn/.config/vis/plugins/vis-ins-completion/complete-dict.lua
> ```

Exactly! In my computer I renamed `vis-ins-completion` to `ins-completion` and changed my local [init.lua](https://github.com/jpaulogg/vis-ins-completion/blob/local/init.lua) to that... So I ended up doing some mess. Sorry about that!

**Comment by ghost** [comment]
I wanted to know why it didn't fail to load the target script when i followed no. 2. Since at that time the path was also wrong.

(Sorry, I used wrong grammar in the previous comment)

**Comment by jpaulogg** [comment]
I didn't noticed that you were asking a question... my english is not very good.

It worked because **I had already fixed the problem** . When you opened this issue I checked `init.lua` and saw the problem, but I thought there was also a problem with vis-plug. After reading the error message more closely I finally understood what was happening.
